### ISSUE TITLE
Publish an archive of light client updates from the beacon chain mainnet.

### ISSUE THREAD

**Issue by zah** [metacraft-labs/DendrETH#4]
The project will generate and maintain a public archive of downloadable light client updates, encoded in SSZ form and covering the history of the beacon chain networks such as Mainnet and Prater since the Altair fork.

The archive will be generated by our [relay node](https://github.com/metacraft-labs/DendrETH/issues/10).

**Comment by zah** [comment]
A starting snapshot and full list of light client updates for Prater have been published here:
https://github.com/metacraft-labs/eth2-light-client-updates

**Comment by grc02** [comment]
A starting snapshot, a full list of light client updates for Mainnet and a bootstrap, for future updates of the list light client updates, have been published here: https://github.com/metacraft-labs/eth2-light-client-updates/tree/main/mainnet
