### ISSUE TITLE
Implement the light client in Nim for WebAssembly based targets

### ISSUE THREAD

**Issue by zah** [metacraft-labs/DendrETH#5]
The light client implementation will be extracted from the Nimbus codebase. We will compare the size and the efficiency of the resulting code against the Rust implementation created by the [Snowbridge project](https://github.com/Snowfork/snowbridge/pull/623) on a real-world client updates obtained from the beacon chain mainnet. The results of the comparison will be reproducible and tracked over time in our CI. 

The tested WebAssembly compiler toolchains will be [Rust][1], [Nim+Clang][2], [NLVM][3].

We should be able to target Substrate, Cosmos, the Internet Computer, Elrond and Solana from the same codebase as well as well as stand-alone WebAssembly rumtimes such as [Wasmer](https://wasmer.io/) for a simplified form of unit testing.

[1]: https://dev.to/nickitax/polkadot-create-your-first-rust-substrate-smart-contract-upload-it-and-interact-with-it-video-143l
[2]: https://github.com/yglukhov/wasmrt
[3]: https://forum.nim-lang.org/t/4779

**Comment by EmilIvanichkovv** [comment]
#25
